name: Add wiki
description: Add a wiki that is part of the IRWA to the bot. 
title: "[Add Wiki]: <wiki name>"
labels: ["wikis"]
projects: ["Roblox-Indie-Wikis/2"]
assignees:
  - SomeMWDev
body:
  - type: markdown
    attributes:
      value: |
        Welcome! Please only request wikis to be added that are part of the Indie Roblox Wiki Alliance (IRWA). To join the alliance, please see [this page](https://indierobloxwikis.org/joining/) for more information.
        Note that a bureucrat on the wiki must either submit this request or confirm it for it to be handled.
  - type: input
    id: wiki_url
    attributes:
      label: Wiki URL
      description: The URL of the main page of the wiki.
      placeholder: ex. mycoolwiki.org
    validations:
      required: true
  - type: dropdown
    id: miraheze
    attributes:
      label: Where is the wiki hosted?
      options:
        - Miraheze
        - Other (Self Hosted etc.)
  - type: checkboxes
    id: captchas
    attributes:
      label: Before You Submit...
      description: Just making sure you are actually a member! 
      options:
        - label: I confirm my wiki that I am submitting is already an existing approved IRWA member. 
